// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CraftingSystem","status":true,"description":"Craft items, weapons and armors based on categorized recipe books.","parameters":{"Categories":"Crafting, Blacksmith, Alchemy","Price Text":"Price","Equip Text":"Equip","Type Text":"Type","Ingredients Text":"Ingredients:","Currency Text":"Currency","Item Crafted Text":"Item crafted:"}},
{"name":"TestScript","status":true,"description":"","parameters":{}}
];
